"""baseline schema

Revision ID: 0001
Revises:
Created: 2026-09-13 23:02:39.428302
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("environment", sa.String(length=64), nullable=False),
        sa.Column("criticality", sa.String(length=32), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("tenant", "name", name="uq_app_tenant_name"),
    )
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_applications_tenant"), ["tenant"], unique=False)

    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_tenant"), ["tenant"], unique=False)
        batch_op.create_index("ix_audit_tenant_created", ["tenant", "created_at"], unique=False)

    op.create_table(
        "components",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("purl", sa.String(length=512), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("ecosystem", sa.String(length=64), nullable=True),
        sa.Column(
            "licenses",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_components")),
        sa.UniqueConstraint("purl", name="uq_component_purl"),
    )
    with op.batch_alter_table("components", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_components_ecosystem"), ["ecosystem"], unique=False)
        batch_op.create_index(batch_op.f("ix_components_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_components_purl"), ["purl"], unique=False)
        batch_op.create_index(batch_op.f("ix_components_version"), ["version"], unique=False)

    op.create_table(
        "detections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rule_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("level", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("source_path", sa.String(length=512), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "tactics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "techniques",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detections")),
        sa.UniqueConstraint("rule_id", name="uq_detections_rule_id"),
    )
    with op.batch_alter_table("detections", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_detections_rule_id"), ["rule_id"], unique=False)

    op.create_table(
        "incident_sequences",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("tenant", name=op.f("pk_incident_sequences")),
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("scenario", sa.String(length=128), nullable=True),
        sa.Column("dedup_key", sa.String(length=64), nullable=False),
        sa.Column("principal", sa.String(length=255), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_reason", sa.Text(), nullable=True),
        sa.Column(
            "tactics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "techniques",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
        sa.UniqueConstraint("tenant", "key", name="uq_incidents_tenant_key"),
    )
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incidents_dedup_key"), ["dedup_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_key"), ["key"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_owner"), ["owner"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_principal"), ["principal"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_risk_score"), ["risk_score"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_scenario"), ["scenario"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_tenant"), ["tenant"], unique=False)
        batch_op.create_index("ix_incidents_tenant_status", ["tenant", "status"], unique=False)

    op.create_table(
        "indicators",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.String(length=512), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "categories",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indicators")),
        sa.UniqueConstraint("type", "value", "provider", name="uq_indicator_identity"),
    )
    with op.batch_alter_table("indicators", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_indicators_type"), ["type"], unique=False)
        batch_op.create_index(batch_op.f("ix_indicators_value"), ["value"], unique=False)

    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tenants_key"), ["key"], unique=True)

    op.create_table(
        "vulnerabilities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("vuln_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("ecosystem", sa.String(length=64), nullable=True),
        sa.Column("package_name", sa.String(length=255), nullable=True),
        sa.Column("affected_range", sa.String(length=255), nullable=True),
        sa.Column("fixed_version", sa.String(length=128), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "references",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vulnerabilities")),
        sa.UniqueConstraint("vuln_id", name="uq_vuln_id"),
    )
    with op.batch_alter_table("vulnerabilities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vulnerabilities_ecosystem"), ["ecosystem"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_vulnerabilities_package_name"), ["package_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_vulnerabilities_severity"), ["severity"], unique=False)
        batch_op.create_index(batch_op.f("ix_vulnerabilities_vuln_id"), ["vuln_id"], unique=False)

    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("rule_id", sa.String(length=128), nullable=False),
        sa.Column("rule_title", sa.String(length=512), nullable=False),
        sa.Column("rule_level", sa.String(length=32), nullable=False),
        sa.Column("rule_revision", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("risk_level", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("principal", sa.String(length=255), nullable=True),
        sa.Column("target_principal", sa.String(length=255), nullable=True),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("session_uid", sa.String(length=128), nullable=True),
        sa.Column("dedup_key", sa.String(length=64), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.Column("is_building_block", sa.Boolean(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=True),
        sa.Column(
            "tactics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "techniques",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_alerts_incident_id_incidents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("tenant", "dedup_key", name="uq_alerts_tenant_dedup"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_dedup_key"), ["dedup_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_hostname"), ["hostname"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_incident_id"), ["incident_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_alerts_is_building_block"), ["is_building_block"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_alerts_principal"), ["principal"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_risk_score"), ["risk_score"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_rule_id"), ["rule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_source_ip"), ["source_ip"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_tenant"), ["tenant"], unique=False)
        batch_op.create_index("ix_alerts_tenant_last_seen", ["tenant", "last_seen"], unique=False)
        batch_op.create_index("ix_alerts_tenant_status", ["tenant", "status"], unique=False)

    op.create_table(
        "component_vulnerabilities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("component_id", sa.String(length=36), nullable=False),
        sa.Column("vulnerability_id", sa.String(length=36), nullable=False),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
            name=op.f("fk_component_vulnerabilities_component_id_components"),
        ),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"],
            ["vulnerabilities.id"],
            name=op.f("fk_component_vulnerabilities_vulnerability_id_vulnerabilities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_component_vulnerabilities")),
        sa.UniqueConstraint("component_id", "vulnerability_id", name="uq_component_vuln"),
    )
    with op.batch_alter_table("component_vulnerabilities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_component_vulnerabilities_component_id"), ["component_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_component_vulnerabilities_vulnerability_id"),
            ["vulnerability_id"],
            unique=False,
        )

    op.create_table(
        "detection_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("detection_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["detection_id"],
            ["detections.id"],
            name=op.f("fk_detection_versions_detection_id_detections"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detection_versions")),
        sa.UniqueConstraint("detection_id", "revision", name="uq_detection_version"),
    )
    with op.batch_alter_table("detection_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_detection_versions_detection_id"), ["detection_id"], unique=False
        )

    op.create_table(
        "incident_notes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["incidents.id"], name=op.f("fk_incident_notes_incident_id_incidents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_notes")),
    )
    with op.batch_alter_table("incident_notes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_incident_notes_incident_id"), ["incident_id"], unique=False
        )

    op.create_table(
        "response_actions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=True),
        sa.Column("playbook", sa.String(length=128), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=True),
        sa.Column(
            "params",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("requested_by", sa.String(length=255), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("rejected_reason", sa.Text(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_response_actions_incident_id_incidents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_response_actions")),
    )
    with op.batch_alter_table("response_actions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_response_actions_incident_id"), ["incident_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_response_actions_playbook"), ["playbook"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_response_actions_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_response_actions_tenant"), ["tenant"], unique=False)

    op.create_table(
        "sboms",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column("spec_version", sa.String(length=32), nullable=True),
        sa.Column("serial_number", sa.String(length=128), nullable=True),
        sa.Column("component_count", sa.Integer(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_sboms_application_id_applications"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sboms")),
    )
    with op.batch_alter_table("sboms", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sboms_application_id"), ["application_id"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_users_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "sbom_components",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sbom_id", sa.String(length=36), nullable=False),
        sa.Column("component_id", sa.String(length=36), nullable=False),
        sa.Column("direct", sa.Boolean(), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
            name=op.f("fk_sbom_components_component_id_components"),
        ),
        sa.ForeignKeyConstraint(
            ["sbom_id"], ["sboms.id"], name=op.f("fk_sbom_components_sbom_id_sboms")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sbom_components")),
        sa.UniqueConstraint("sbom_id", "component_id", name="uq_sbom_component"),
    )
    with op.batch_alter_table("sbom_components", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sbom_components_component_id"), ["component_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sbom_components_sbom_id"), ["sbom_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sbom_components", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sbom_components_sbom_id"))
        batch_op.drop_index(batch_op.f("ix_sbom_components_component_id"))

    op.drop_table("sbom_components")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("sboms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sboms_application_id"))

    op.drop_table("sboms")
    with op.batch_alter_table("response_actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_response_actions_tenant"))
        batch_op.drop_index(batch_op.f("ix_response_actions_status"))
        batch_op.drop_index(batch_op.f("ix_response_actions_playbook"))
        batch_op.drop_index(batch_op.f("ix_response_actions_incident_id"))

    op.drop_table("response_actions")
    with op.batch_alter_table("incident_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incident_notes_incident_id"))

    op.drop_table("incident_notes")
    with op.batch_alter_table("detection_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_detection_versions_detection_id"))

    op.drop_table("detection_versions")
    with op.batch_alter_table("component_vulnerabilities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_component_vulnerabilities_vulnerability_id"))
        batch_op.drop_index(batch_op.f("ix_component_vulnerabilities_component_id"))

    op.drop_table("component_vulnerabilities")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index("ix_alerts_tenant_status")
        batch_op.drop_index("ix_alerts_tenant_last_seen")
        batch_op.drop_index(batch_op.f("ix_alerts_tenant"))
        batch_op.drop_index(batch_op.f("ix_alerts_status"))
        batch_op.drop_index(batch_op.f("ix_alerts_source_ip"))
        batch_op.drop_index(batch_op.f("ix_alerts_rule_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_risk_score"))
        batch_op.drop_index(batch_op.f("ix_alerts_principal"))
        batch_op.drop_index(batch_op.f("ix_alerts_is_building_block"))
        batch_op.drop_index(batch_op.f("ix_alerts_incident_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_hostname"))
        batch_op.drop_index(batch_op.f("ix_alerts_dedup_key"))

    op.drop_table("alerts")
    with op.batch_alter_table("vulnerabilities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vulnerabilities_vuln_id"))
        batch_op.drop_index(batch_op.f("ix_vulnerabilities_severity"))
        batch_op.drop_index(batch_op.f("ix_vulnerabilities_package_name"))
        batch_op.drop_index(batch_op.f("ix_vulnerabilities_ecosystem"))

    op.drop_table("vulnerabilities")
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenants_key"))

    op.drop_table("tenants")
    with op.batch_alter_table("indicators", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_indicators_value"))
        batch_op.drop_index(batch_op.f("ix_indicators_type"))

    op.drop_table("indicators")
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_index("ix_incidents_tenant_status")
        batch_op.drop_index(batch_op.f("ix_incidents_tenant"))
        batch_op.drop_index(batch_op.f("ix_incidents_status"))
        batch_op.drop_index(batch_op.f("ix_incidents_scenario"))
        batch_op.drop_index(batch_op.f("ix_incidents_risk_score"))
        batch_op.drop_index(batch_op.f("ix_incidents_principal"))
        batch_op.drop_index(batch_op.f("ix_incidents_owner"))
        batch_op.drop_index(batch_op.f("ix_incidents_key"))
        batch_op.drop_index(batch_op.f("ix_incidents_dedup_key"))

    op.drop_table("incidents")
    op.drop_table("incident_sequences")
    with op.batch_alter_table("detections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_detections_rule_id"))

    op.drop_table("detections")
    with op.batch_alter_table("components", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_components_version"))
        batch_op.drop_index(batch_op.f("ix_components_purl"))
        batch_op.drop_index(batch_op.f("ix_components_name"))
        batch_op.drop_index(batch_op.f("ix_components_ecosystem"))

    op.drop_table("components")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_tenant_created")
        batch_op.drop_index(batch_op.f("ix_audit_log_tenant"))
        batch_op.drop_index(batch_op.f("ix_audit_log_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_action"))

    op.drop_table("audit_log")
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applications_tenant"))

    op.drop_table("applications")
    # ### end Alembic commands ###
