"""multi-analyst operations

Revision ID: 0002
Revises: 0001
Created: 2026-09-13 23:02:51.387732
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("tenant", "slug", name="uq_teams_tenant_slug"),
    )
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_teams_slug"), ["slug"], unique=False)
        batch_op.create_index(batch_op.f("ix_teams_tenant"), ["tenant"], unique=False)

    op.create_table(
        "team_members",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("team_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_team_members_team_id_teams")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_team_members_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_members")),
        sa.UniqueConstraint("team_id", "user_id", name="uq_team_members_team_user"),
    )
    with op.batch_alter_table("team_members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_team_members_team_id"), ["team_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_team_members_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("assignee_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("team_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("version", sa.Integer(), server_default="1", nullable=False))
        batch_op.add_column(sa.Column("waiting_until", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("waiting_reason", sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f("ix_incidents_assignee_id"), ["assignee_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_team_id"), ["team_id"], unique=False)
        batch_op.create_index("ix_incidents_team_status", ["team_id", "status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_incidents_waiting_until"), ["waiting_until"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_incidents_assignee_id_users"), "users", ["assignee_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_incidents_team_id_teams"), "teams", ["team_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_incidents_team_id_teams"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_incidents_assignee_id_users"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_incidents_waiting_until"))
        batch_op.drop_index("ix_incidents_team_status")
        batch_op.drop_index(batch_op.f("ix_incidents_team_id"))
        batch_op.drop_index(batch_op.f("ix_incidents_assignee_id"))
        batch_op.drop_column("waiting_reason")
        batch_op.drop_column("waiting_until")
        batch_op.drop_column("version")
        batch_op.drop_column("acknowledged_at")
        batch_op.drop_column("team_id")
        batch_op.drop_column("assignee_id")

    with op.batch_alter_table("team_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_team_members_team_id"))

    op.drop_table("team_members")
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_teams_tenant"))
        batch_op.drop_index(batch_op.f("ix_teams_slug"))

    op.drop_table("teams")
    # ### end Alembic commands ###
