"""sla clocks

Revision ID: 0003
Revises: 0002
Created: 2026-09-21 02:42:57.935784
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_ack_due', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('sla_resolve_due', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('sla_escalated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_incidents_sla_ack_due'), ['sla_ack_due'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_sla_resolve_due'), ['sla_resolve_due'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_sla_resolve_due'))
        batch_op.drop_index(batch_op.f('ix_incidents_sla_ack_due'))
        batch_op.drop_column('sla_escalated_at')
        batch_op.drop_column('sla_resolve_due')
        batch_op.drop_column('sla_ack_due')

    # ### end Alembic commands ###
