"""threaded comments and watchers

Revision ID: 0004
Revises: 0003
Created: 2026-09-21 04:56:22.752798
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_watchers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_watchers_incident_id_incidents')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_incident_watchers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_watchers')),
    sa.UniqueConstraint('incident_id', 'user_id', name='uq_incident_watchers_incident_user')
    )
    with op.batch_alter_table('incident_watchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_watchers_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_watchers_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('incident_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('mentions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_incident_notes_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_notes_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_incident_notes_parent_id_incident_notes'), 'incident_notes', ['parent_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_incident_notes_author_id_users'), 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_notes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_incident_notes_author_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_incident_notes_parent_id_incident_notes'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_incident_notes_parent_id'))
        batch_op.drop_index(batch_op.f('ix_incident_notes_author_id'))
        batch_op.drop_column('edited_at')
        batch_op.drop_column('mentions')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('incident_watchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_watchers_user_id'))
        batch_op.drop_index(batch_op.f('ix_incident_watchers_incident_id'))

    op.drop_table('incident_watchers')
    # ### end Alembic commands ###
