"""incident links

Revision ID: 0006
Revises: 0005
Created: 2026-09-22 18:42:37.608186
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant', sa.String(length=64), nullable=False),
    sa.Column('source_incident_id', sa.String(length=36), nullable=False),
    sa.Column('target_incident_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_incident_id'], ['incidents.id'], name=op.f('fk_incident_links_source_incident_id_incidents')),
    sa.ForeignKeyConstraint(['target_incident_id'], ['incidents.id'], name=op.f('fk_incident_links_target_incident_id_incidents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_links')),
    sa.UniqueConstraint('source_incident_id', 'target_incident_id', 'relationship', name='uq_incident_links_edge')
    )
    with op.batch_alter_table('incident_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_links_source_incident_id'), ['source_incident_id'], unique=False)
        batch_op.create_index('ix_incident_links_target', ['target_incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_links_tenant'), ['tenant'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_links_tenant'))
        batch_op.drop_index('ix_incident_links_target')
        batch_op.drop_index(batch_op.f('ix_incident_links_source_incident_id'))

    op.drop_table('incident_links')
    # ### end Alembic commands ###
